import {test,expect} from '@playwright/test';
test('reading stays within 320/390/768/1280 and 200 percent equivalent viewports',async({page})=>{
 for(const width of [320,390,640,768,1024,1280,1440])for(const theme of ['light','dark']){await page.setViewportSize({width,height:900});await page.addInitScript(t=>{localStorage.setItem('theme',t);localStorage.setItem('firefly-effects','off');},theme);for(const path of ['/','/notes/reinforcement-learning-lec3-bellman-optimality/','/notes/compiler-principles-lec5/','/search/']){await page.goto(path);await expect(page.locator('h1')).toHaveCount(1);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`${width} ${theme} ${path}`).toBe(true);}}
});
test('keyboard reaches main content and hidden navigation cannot receive focus',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/notes/operating-systems-lec0/');await page.keyboard.press('Tab');await expect(page.getByRole('link',{name:'跳到正文'})).toBeFocused();await page.keyboard.press('Enter');await expect(page.locator('main')).toBeFocused();
 expect(await page.locator('#nav-menu-panel').evaluate(e=>e.hasAttribute('inert'))).toBe(true);
 await page.locator('.knowledge-context-inline>summary').focus();await page.keyboard.press('Enter');await expect(page.locator('#topic-nav-inline')).toBeVisible();await expect(page.locator('#topic-nav-sidebar')).toBeHidden();
 await page.locator('#search-switch').focus();await page.keyboard.press('Enter');await expect(page.locator('#search-panel')).toBeVisible();await page.keyboard.press('Escape');await expect(page.locator('#search-switch')).toBeFocused();
 await page.locator('#effects-toggle').focus();await page.keyboard.press('Enter');await expect(page.locator('#effects-toggle')).toHaveAttribute('aria-pressed','true');
});
test('no JavaScript preserves article, course order, pagination, hash and search fallback',async({browser})=>{
 const context=await browser.newContext({javaScriptEnabled:false,viewport:{width:390,height:844}});const p=await context.newPage();await p.goto('/notes/operating-systems-lec0/');await expect(p.locator('h1')).toHaveText('Lec0: 课程介绍与成绩');await p.locator('summary').filter({hasText:'文章目录'}).click();await p.getByRole('navigation',{name:'文章目录',exact:true}).getByRole('link').first().click();expect(new URL(p.url()).hash.length).toBeGreaterThan(1);
 await p.goto('/courses/operating-systems/');await expect(p.locator('.post-card-title')).toHaveCount(13);await p.goto('/notes/page/2/');await expect(p.locator('.post-card-title')).toHaveCount(20);await p.goto('/search/');await expect(p.locator('noscript p')).toBeVisible();await expect(p.getByRole('navigation',{name:'搜索备用入口'})).toBeVisible();await context.close();
});
test('desktop focused search and keyboard theme controls fit their viewport',async({page})=>{await page.setViewportSize({width:1280,height:900});await page.goto('/');await page.locator('#search-input-desktop').focus();await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.locator('#scheme-switch').focus();await page.keyboard.press('Enter');await expect(page.locator('#theme-mode-panel')).toBeVisible();await page.keyboard.press('Escape');await expect(page.locator('#scheme-switch')).toBeFocused();});
test('the small shared avatar does not download a multi-megabyte original',async({page})=>{await page.goto('/');const src=await page.locator('#navbar img').first().getAttribute('src');const response=await page.request.get(src!);expect((await response.body()).byteLength).toBeLessThan(100000);});
