import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,mkdir,readFile,writeFile,copyFile,rm,readdir} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import {execFileSync} from 'node:child_process';import {buildManifest,convertContent} from '../../scripts/migration/convert';import {verifyMigration} from '../../scripts/verify-site';
test('immutable acceptance detects omissions, corrupt assets and scope changes using isolated source fixtures',async()=>{
 const root=await mkdtemp(join(tmpdir(),'firefly-frozen-'));const source=join(root,'source'),target=join(root,'target');
 try{await mkdir(join(source,'content/posts'),{recursive:true});execFileSync('git',['init','-q'],{cwd:source});execFileSync('git',['-c','user.name=Fixture','-c','user.email=fixture@example.test','-c','commit.gpgsign=false','commit','--allow-empty','-qm','fixture'],{cwd:source});
 await writeFile(join(source,'content/posts/a.md'),'---\ntitle: A\nid: a\nslug: a\n---\nFixture body');await writeFile(join(source,'content/posts/typora-test.md'),'---\ntitle: Private demo\nid: typora-test\nslug: typora-test\n---\nDemo body');await writeFile(join(source,'content/posts/image.png'),Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==','base64'));
 const manifest=await buildManifest(source);await convertContent(manifest,{sourceRoot:source,targetRoot:target,dryRun:true});await assert.rejects(readdir(target),/ENOENT/);await convertContent(manifest,{sourceRoot:source,targetRoot:target,dryRun:false});assert.deepEqual(await verifyMigration(manifest,target),{records:2,published:1,assets:1,errors:[]});assert.deepEqual((await convertContent(manifest,{sourceRoot:source,targetRoot:target,dryRun:false})).written,[]);
 const image=manifest.assets[0];await writeFile(join(target,image.sourcePath),'corrupt');assert.ok((await verifyMigration(manifest,target)).errors.some(e=>e.includes(image.sourcePath)));await copyFile(join(source,'content/posts',image.sourcePath),join(target,image.sourcePath));
 assert.ok((await verifyMigration({...manifest,records:manifest.records.slice(1)},target)).errors.some(e=>e.includes('missing source record')));
 const demo=manifest.records.find(r=>r.slug==='typora-test')!;const path=join(target,demo.targetPath);await writeFile(path,(await readFile(path,'utf8')).replace('visibility: "unlisted"','visibility: "published"'));assert.ok((await verifyMigration(manifest,target)).errors.some(e=>e.includes('visibility')));
 }finally{await rm(root,{recursive:true,force:true});}
});
